sudo: required
language: go
go:
  - '1.10'
before_install:
  - go get -t -v ./...
jobs:
  include:
    - stage: docker-latest
      script:
        - docker build -t arturom/monarchs:latest .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push arturom/monarchs:latest
        
    - stage: docker-branch
      script:
        - docker build -t arturom/monarchs:$TRAVIS_BRANCH .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push arturom/monarchs:$TRAVIS_BRANCH

    - stage: docker-pr
      script:
        - docker build -t arturom/monarchs:PR-$TRAVIS_PULL_REQUEST .
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push arturom/monarchs:PR-$TRAVIS_PULL_REQUEST

branches:
  only:
    - master
    - "/^v.*$/"
stages:
  - name: docker-latest
    if: branch == master AND type != pull_request

  - name: docker-branch
    if: branch != master AND type != pull_request

  - name: docker-pr
    if: type == pull_request

