apiVersion: v1
kind: Service
metadata:
  name: {{ template "monarchs.fullname" . }}
  labels:
    app: {{ template "monarchs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if (.Values.external.url) }}
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.service.url }}"
    {{- end }}
    {{- if eq .Values.elb.type "internal" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    {{- end }}
    {{- if (.Values.elb.ssl_cert) }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "{{ .Values.service.externalPort }}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.elb.ssl_cert }}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    {{- end }}
    {{- range $key, $value := .Values.service.extra_annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if (eq .Values.elb.type "internal") or (eq .Values.elb.type "external") }}
  type: LoadBalancer
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "monarchs.name" . }}
    release: {{ .Release.Name }}
